### ISSUE TITLE
2.0.5 Cocoapods installation failed

### ISSUE THREAD

**Issue by hitbear518** [AlexanderZaytsev/react-native-i18n#124]
After upgrade to 2.0.5, cocoapods installation can't build, there's an error `'React/RCTBridgeModule.h' file not found` in RNI18n.h.

I noticed 208ee2192f84803c1eed37f41526b8722207655a removed `s.dependency "React"` which caused this problem, but I don't know why removed this dependency

**Comment by chrismllr** [comment]
Can confirm - Each build throws the above error, backed down version to `2.0.4` and build succeeds

**Comment by studyroz** [comment]
Seems https://github.com/AlexanderZaytsev/react-native-i18n/commit/208ee2192f84803c1eed37f41526b8722207655a causes this issue.

Why the dependency was removed from podspec ?

**Comment by zoontek** [comment]
@studyroz Because the React pod was obsolete (0.13RC) and has been deprecated. Check https://cocoapods.org/?q=react

This is greatly detailled in the react native documentation: http://facebook.github.io/react-native/releases/0.48/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies

**Comment by hitbear518** [comment]
I'm not familiar with CocoaPods, but for this situation, I already installed React through local podspec, will it install two React dependencies if you add s.dependency = "React"?

also there's a newer version of React podspec to check here in Artsy's repo https://github.com/artsy/Specs/blob/master/React/0.45.0-rc.2/React.podspec.json

**Comment by zoontek** [comment]
Yes, you will have both. The version from your package.json and the deprecated version from cocoapods.

**Comment by zoontek** [comment]
I prefer an update of this project README than declare a deprecated pod in the podspec.
I'm currently on holidays, so I'll do it when I'm come back (or will merge a PR if I have one) 🙂

**Comment by studyroz** [comment]
For 2.0.5, by `pod install` from this Podfile, my iOS project compilation fails.
~~~ruby
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

node_modules_path = '../node_modules'
react_subspecs = %w(DevSupport BatchedBridge RCTAnimation RCTActionSheet RCTGeolocation RCTImage RCTNetwork RCTLinkingIOS RCTText RCTVibration)
react_path = File.join(node_modules_path, 'react-native')
yoga_path = File.join(react_path, 'ReactCommon/yoga')

target 'MyProject' do

  pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'React', :path => react_path, :subspecs => react_subspecs
  pod 'Yoga', :path => yoga_path

  pod 'RNI18n', :path => File.join(node_modules_path, 'react-native-i18n')

  target 'MyProjectTests'
end
~~~

But 2.0.4 works without any problem. And the local `React` pod is correctly used by Cocoapods.

**Comment by zoontek** [comment]
@studyroz Can you provide the compilation error?

**Comment by studyroz** [comment]
`'React/RCTBridgeModule.h' file not found in RNI18n.m`

Similar to @hitbear518 's issue.

**Comment by zoontek** [comment]
I rolled this back: https://github.com/AlexanderZaytsev/react-native-i18n/releases/tag/v2.0.6 , maybe https://github.com/facebook/react-native/pull/15460 will provide a proper solution.

**Comment by rborn** [comment]
@AlexanderZaytsev @zoontek  I still have issues with this 😢 
My app has airbnb's google maps in it, and that's my Podfile after linking i18n:

~~~
platform :ios, '8.0'
target 'Uoc' do
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
pod 'GoogleMaps'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

end
~~~

it will start complaining about duplicate modules

~~~
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Work/clients/current/uoc/app/node_modules/react-native/package.json collides with /Work/clients/current/uoc/app/ios/Pods/React/package.json
~~~
I fixed this by removing `s.dependency "React"` from **RNI18N.podspec**  and add this to my Podfile

~~~
pod 'React', :path => '../node_modules/react-native'
~~~

And now everything goes smooth 😸 

Env:

~~~
        "react": "16.0.0",
        "react-native": "0.50.3",
        "react-native-i18n": "^2.0.9",

$ pod --version
1.3.1

~~~

I could try a  PR but I don't know how to instruct `react-native link` to add that line in the Podfile 😢

**Comment by zoontek** [comment]
@rborn You can write a PR just to remove `s.dependency "React"` from the podfile (it has been deprecated, by the way)

**Comment by rborn** [comment]
@zoontek yes, but without the new line in the project's Podfile it won't build.
I can alter the readme too if this is good enough

**Comment by zoontek** [comment]
@rborn No need, it's currently in the official documentation: https://facebook.github.io/react-native/releases/0.23/docs/embedded-app-ios.html#install-react-native-using-cocoapods

**Comment by rborn** [comment]
@zoontek #147 
Thanks :)
