### ISSUE TITLE
Add ability to use React components in formatting?

### ISSUE THREAD

**Issue by henrikra** [AlexanderZaytsev/react-native-i18n#142]
## Motivation
Situation where you have a link inside of string that you have to translate like this:

![image](https://user-images.githubusercontent.com/12229968/28072080-834bc45e-665a-11e7-97c6-83a4a1964a62.png)

I tried to look from the api but I could not find a function that would allow me to pass component to localisation string. It just prints for example `You have to [object Object] in order to use our app.`

**Comment by henrikra** [comment]
Can you provide example?

**Comment by zoontek** [comment]
```js
<View style={{ flexDirection: 'row' }}>
  <Text>{t('text.before.break')}</Text>
  <YourTextComponent style={{ marginHorizontal: 2 }} />
  <Text>{t('text.after.break')}</Text>
</View>
```

Something like this

**Comment by fvicente** [comment]
I don't think @zoontek 's example is a good internationalization practice. Depending on the language, and what you're trying to internationalize, your component might change the position (component might be moved at the end or beginning, single words may become multiple words, etc.), that's why interpolation should be the right solution. Yahoo's react-intl supports this kind of 'rich text' interpolation, but apparently the owner of this project said that is not on the scope of this project.
Fortunately, someone one posted a function that does what this library should by default:
https://github.com/AlexanderZaytsev/react-native-i18n/issues/38#issuecomment-312888888
