### ISSUE TITLE
Quick fix for RNI18n.getLanguages error

### ISSUE THREAD

**Issue by sofiane-soufi** [AlexanderZaytsev/react-native-i18n#143]
Hi everyone,

If you ever encounter this error: **undefined is not an object (evaluating 'RNI18n.getLanguages')**, it means the module couldn't get properly the default language.

To fix it, in the file index.js (might be located in node_modules/react-native-i18n/), replace the following lines:

`
I18nJs.locale = RNI18n.languages[0]; // Line 7`
`
export const getLanguages = RNI18n.getLanguages; // Line 12
`

by

`
I18nJs.locale = (RNI18n) ? RNI18n.languages[0] : "";`
`
export const getLanguages = (RNI18n) ? RNI18n.getLanguages : () => {};
`

If there's anyway to change it on the project, it would help a lot of people! @AlexanderZaytsev 

Hope it helped some of you guys out there! 👍

**Comment by kavykun** [comment]
Thanks @sofiane-soufi.

This worked for me.

**Comment by albertogasparin** [comment]
I had the same problem with RN 0.50, however I think your solution is problematic. In my case, for instance, the problem was that react-native-i18n was not properly linked, even if I run the `link` command. Indeed, the RNI18n Xcode project and library were not successfully added (I had to do it manually). 
With your fix my project was running, however native api calls might not work. I suggest the author should provide a better error message if the object RNI18n is undefined, as currently the console.log is not visible because the app throws.

**Comment by sofiane-soufi** [comment]
@albertogasparin you're right, that's why I put it as quick fix, I'll investigate more to propose a better solution for it, and you're totally right about your comment, react-native-i18n doesn't link properly.

thank you!

**Comment by ecnaidar** [comment]
@sofiane-soufi 
Better error handling with fallbacks is required for that part. Your solution is an error suppression rather than a fix and merging it would bring a lot more problems (not knowing that linking is broken)
I was getting the error while running tests and fixed it by mocking the RNI18n Native Module (which should be present 100% on the device if you are using the library but is absent in test environment)

In tests setup I did 
```javascript

import { NativeModules } from "react-native";

const languages = ['en'] /// your desired locales here if needed

NativeModules.RNI18n = {
    languages,
    getLanguages: () => languages
};
```

**Comment by sofiane-soufi** [comment]
@ecnaidar Even better solution, prevents changing the module itself. +1.

**Comment by zoontek** [comment]
@sofiane-soufi It's not a fix, it's error suppression. Like @albertogasparin said, it will simply silent error if the module is not linked properly.

I already talked about this multiples time, and a mock is present in the example project to help you writing tests.
