### ISSUE TITLE
Error when unit testing component

### ISSUE THREAD

**Issue by rajeshsivakumar** [AlexanderZaytsev/react-native-i18n#30]
I get the following error when unit testing a component that uses I18n:

node_modules/react-native-i18n/index.js:7
I18n.locale = RNI18n.locale.replace(/_/, '-');
                    ^

TypeError: Cannot read property 'locale' of undefined

Is there a way to set a locale before unit testing.

Thanks!

**Comment by romanlv** [comment]
Until this bug is fixed you can mock this dependency 

// in mocha.opts: --require ./test/support/common
```js
// common.js

import mockery from 'mockery';

mockery.enable();
mockery.warnOnUnregistered(false);

mockery.registerMock('react-native-i18n', {
  t: k => k,
});

```

**Comment by mmazzarolo** [comment]
#27 should have fixed that, let me know

**Comment by chris-verclytte** [comment]
Indeed #27 should fix. Is a new release planned in few days ?

**Comment by mmazzarolo** [comment]
@chris-verclytte 
Just pushed a [new beta release](https://github.com/AlexanderZaytsev/react-native-i18n/releases/tag/v0.1.0-beta.0).  
I tagged it as beta because it has been a long time since the last release and I would like to test it a bit.  
Let me know if it works correctly for you! (It seems to run fine for me)

**Comment by chris-verclytte** [comment]
Super ! Thank you, I will give it a try and keep you updated.

**Comment by mmazzarolo** [comment]
@chris-verclytte 👍
