### ISSUE TITLE
Overriding happening when different translation sets present

### ISSUE THREAD

**Issue by Naoto-Ida** [AlexanderZaytsev/react-native-i18n#55]
First off, I'm really enjoying this lib.

I'm running into an issue where I have two translation sets.
One belongs to my main app, and the other belongs to a package containing lots of reusable components with translated text in them.

They both import `react-native-i18n`, then set translations and `fallbacks=true`.

The problem seems to be that one of them is overriding the other and ignoring the values.
I'm ok with 'dog' in main app being 'dog', but overrode in the package to 'woof' or something if I specify, but right now the translations I set in the main app are completely ignored.

**Comment by mmazzarolo** [comment]
Never encountered a similar case... I guess the problem lies in the fact that both your application and the module you're using share the same I18n package (which sounds correct) but I'm not aware of an easy solution at the moment.  
Can you name the library that is giving you problems? It's a bit weird using i18n inside a library in my opinion.

**Comment by Naoto-Ida** [comment]
@mmazzarolo Yes, that seems to be whats causing issues.

We have a common set of RN components for our apps packaged into one package, along with the translations that are displayed in buttons, etc. It seems more of an issue to do with `i18n-js`.
