### ISSUE TITLE
MainApplication.java:6: error: package com.i18n.reactnativei18n does not exist

### ISSUE THREAD

**Issue by kianhuat** [AlexanderZaytsev/react-native-i18n#95]
After installed to latest version @2.0.1 and run android, I hit error as below:

> /Users/sangai/Projects/React Native/testproj/android/app/src/main/java/com/testproj/MainApplication.java:6: error: package com.i18n.reactnativei18n does not exist
> import com.i18n.reactnativei18n.ReactNativeI18n;
>                                ^
> /Users/sangai/Projects/React Native/testproj/android/app/src/main/java/com/testproj/MainApplication.java:32: error: cannot find symbol
>             new ReactNativeI18n(),
>                 ^
>   symbol: class ReactNativeI18n
> 2 errors
> :app:compileDebugJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.
> 

Then, I run "npm list":

> ├─┬ react-native-i18n@2.0.1
> │ └── i18n-js@0.0.0 (git://github.com/fnando/i18n-js.git#b8fb918c827a2d3bbe187372e47bbe1a7a6c4c19)

Is it correct on the dependency package "i18n-js@0.0.0" that installed?

Thanks.

**Comment by zoontek** [comment]
@kianhuat The namespace change on v2 (explain partially the major version bump)
It's now `import com.AlexanderZaytsev.RNI18n.RNI18nPackage`. Check the doc at android install.

Yes because i18n-js is not on npm. We are using the github release tag: https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/package.json#L19

**Comment by kianhuat** [comment]
@zoontek Thanks for help.
